name: pyprecis-environment
channels:
     - conda-forge
dependencies:
  - python=3.6.10
  - iris=2.4.0
  - numpy=1.17.4
  - matplotlib=3.1.3
  - nc-time-axis=1.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - dask=2.11.0
  - notebook=5.7.8
  - mo_pack=0.2.0
