name: pyprecis
channels:
  - conda-forge
dependencies:
  - python
  - iris=3.6
  - iris-sample-data
  - numpy
  - matplotlib
  - nc-time-axis
  - jupyter
  - dask
  - boto3
  - tqdm
  - cdo
  - nco
  - ncview
  - pre-commit
